---
- hosts: newuser

  become: yes
  become_method: sudo
  tasks:
    - name: install httpd
      action: yum name=httpd state=installed

    - name: Copy html
      copy: src=index.html dest=/var/www/html/index.html

    - name: start apache
      service:
        name: httpd
        state: restarted
